// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLookupUserTable = `-- name: CreateLookupUserTable :exec
CREATE TABLE IF NOT EXISTS lookup_users (
    user_uuid uuid PRIMARY KEY NOT NULL,
    user_name varchar(16) NOT NULL
)
`

func (q *Queries) CreateLookupUserTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createLookupUserTable)
	return err
}

const createPunishType = `-- name: CreatePunishType :exec
DO $$ BEGIN
    IF to_regtype('punishtype') IS NULL THEN
        CREATE TYPE friendstatus AS enum (
            'BAN',
            'MUTE'
        );
    END IF;
END $$
`

func (q *Queries) CreatePunishType(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createPunishType)
	return err
}

const createPunishUsersTable = `-- name: CreatePunishUsersTable :exec
CREATE TABLE IF NOT EXISTS punished_users (
    id SERIAL PRIMARY KEY,
    user_uuid uuid NOT NULL,
    punish_type punishtype NOT NULL,
    time_ends time NOT NULL
)
`

func (q *Queries) CreatePunishUsersTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createPunishUsersTable)
	return err
}

const logIntoLookupTable = `-- name: LogIntoLookupTable :exec
INSERT INTO lookup_users (
    user_uuid, user_name
) VALUES (
    $1, $2
)
ON CONFLICT(user_uuid)
DO UPDATE SET
user_name = $2
`

type LogIntoLookupTableParams struct {
	UserUuid uuid.UUID
	UserName string
}

func (q *Queries) LogIntoLookupTable(ctx context.Context, arg LogIntoLookupTableParams) error {
	_, err := q.db.ExecContext(ctx, logIntoLookupTable, arg.UserUuid, arg.UserName)
	return err
}

const punishPlayer = `-- name: PunishPlayer :exec
INSERT INTO punished_users (
    user_uuid, punish_type, time_ends
) VALUES (
    $1, $2, $3
)
`

type PunishPlayerParams struct {
	UserUuid   uuid.UUID
	PunishType Punishtype
	TimeEnds   time.Time
}

func (q *Queries) PunishPlayer(ctx context.Context, arg PunishPlayerParams) error {
	_, err := q.db.ExecContext(ctx, punishPlayer, arg.UserUuid, arg.PunishType, arg.TimeEnds)
	return err
}
